### ISSUE TITLE
将Split 改用SplitN

### ISSUE THREAD

**Issue by doylecnn** [leoleoasd/tg_queue_bot#1]
这里注释提到
https://github.com/leoleoasd/tg_queue_bot/blob/97fa5f32577810356ced38ec8867ae955a154e83/main.go#L118 

那其实，不如将99行的strings.Split 改为 [strings.SplitN](https://golang.org/pkg/strings/#SplitN)
https://github.com/leoleoasd/tg_queue_bot/blob/97fa5f32577810356ced38ec8867ae955a154e83/main.go#L99

**Comment by leoleoasd** [comment]
有道理，不过一堆地方都要改，只有有时间再说吧hhhh
比如现在的queue的args属性就是这个split后的东西，如果要改的话就应该顺便一起改成比如private info 和public info
现在是默认args的第一个是private

**Comment by leoleoasd** [comment]
大佬有时间的话可以发个pr 没时间的话我之后慢慢改吧
